ADMINISTRATIVE_HRIS_EMPLOYEE_CREATE = "administrative.hris.employee.create.v1"
ADMINISTRATIVE_HRIS_EMPLOYEE_DEACTIVATE = (
    "administrative.hris.employee.deactivate.v1"
)
ADMINISTRATIVE_IAM_IDENTITY_CREATE = "administrative.iam.identity.create.v1"
ADMINISTRATIVE_IAM_IDENTITY_DISABLE = "administrative.iam.identity.disable.v1"
ADMINISTRATIVE_IAM_SESSIONS_REVOKE = "administrative.iam.sessions.revoke.v1"

OFFBOARDING_CUTOVER_CAPABILITIES = frozenset(
    {
        ADMINISTRATIVE_HRIS_EMPLOYEE_DEACTIVATE,
        ADMINISTRATIVE_IAM_IDENTITY_DISABLE,
        ADMINISTRATIVE_IAM_SESSIONS_REVOKE,
    }
)

__all__ = [
    "ADMINISTRATIVE_HRIS_EMPLOYEE_CREATE",
    "ADMINISTRATIVE_HRIS_EMPLOYEE_DEACTIVATE",
    "ADMINISTRATIVE_IAM_IDENTITY_CREATE",
    "ADMINISTRATIVE_IAM_IDENTITY_DISABLE",
    "ADMINISTRATIVE_IAM_SESSIONS_REVOKE",
    "OFFBOARDING_CUTOVER_CAPABILITIES",
]
